name: 🚀 Feature Request
description: Have an idea? Pitch it!
title: "[Feat]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### 💡 Feature Proposal
        Help us make Vivi Music even more awesome.

  - type: dropdown
    id: category
    attributes:
      label: 🏷️ Category
      options:
        - ✨ New Feature
        - 🎨 UI / Design Improvement
        - ⚡ Performance / Optimization
        - 🎧 Audio Experience
        - 🌐 Translation / Localization
        - 🔧 Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 The Pitch
      description: Describe your idea clearly. How should it work?
      placeholder: "I would love to see..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🤝 Problem Solved
      description: Why is this feature necessary? What problem does it solve for you?
      placeholder: "Currently, it is difficult to..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🎨 Mockups / Screenshots / Extras
      description: Drop images or sketches here if you have them!
