name: Nightly GMS Release Build

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'
      - 'fastlane/**'
      - 'assets/**'
      - '.github/**/*.md'
  schedule:
    - cron: '0 0 * * *' # Every night at 00:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build_nightly:
    name: Build Universal GMS Release
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Setup FFTW for Android
        uses: ./.github/actions/setup-fftw

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate debug.keystore
        run: |
          mkdir -p ~/.android
          keytool -genkey -v \
            -keystore ~/.android/debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Build Universal GMS Release APK
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_SECRET: ${{ secrets.LASTFM_SECRET }}
        run: |
          ./gradlew assembleUniversalGmsRelease --no-configuration-cache --console=plain --warning-mode summary -x lint

      - name: Sign APK
        uses: ilharp/sign-android-release@v2.0.0
        with:
          releaseDir: app/build/outputs/apk/universalGms/release/
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Prepare Artifact
        run: |
          OUTPUT_DIR="app/build/outputs/apk/universalGms/release"
          mkdir -p "$OUTPUT_DIR/out"
          find "$OUTPUT_DIR" -name "*-signed.apk" -o -name "*-unsigned-signed.apk" | xargs -I{} mv {} "$OUTPUT_DIR/out/vivi-music-gms-nightly.apk"

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: vivi-music-gms-nightly
          path: app/build/outputs/apk/universalGms/release/out/*.apk
